name: Yi-Ta Lu
url: http://example.org
description: (Incoming) Postdoctoral Researcher, Max Planck Institute for Evolutionary Anthropology

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
