name: Yi-Ta Lu
url: http://example.org
description: Ph.D., Stony Brook University

permalink: /:year/:month/:day/:title/
paginate: 10

gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
